package mta.ltnc.BookStore.repositories;

import mta.ltnc.BookStore.dto.client.OrderDto;
import mta.ltnc.BookStore.entity.Order;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Repository
public interface OrderRepository extends JpaRepository<Order, Long>, JpaSpecificationExecutor<Order> {
    @Query("SELECT new mta.ltnc.BookStore.dto.client.OrderDto(o) FROM Order o WHERE o.user.id = :userId ORDER BY o.createdDate")
    List<OrderDto> findAllByUserId(@Param("userId") Long userId);

}
